[ -f ~/.bashrc ] && source ~/.bashrc

#export LD_LIBRARY_PATH=/usr/local/lib
#export LD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH

export PATH=~/bin:$PATH

export GOPATH=$HOME/workspace/:$GOPATH

# MacPorts Installer addition on 2014-10-20_at_17:05:32: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

